CREATE TABLE PhuongTien (
    VehicleID NVARCHAR(50) PRIMARY KEY, 
    VehicleType NVARCHAR(100) NOT NULL, 
    LicensePlate NVARCHAR(50) NOT NULL UNIQUE,
    Brand NVARCHAR(100) NULL,
    ApartmentID NVARCHAR(50) NULL FOREIGN KEY REFERENCES Canho(ApartmentID)
);